language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
 - python setup.py -q install

# setup different django versions
env:

# command to run tests
script:
  python django_orm_sugar.py
