version: '2'

services:
  redis:
    image: redis:2.8
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  fan:
    build: .
    command: green
